RechargeProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]

app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
app_name='app1'
urlpatterns = [
    path('', views.RechargeCardV.index, name='index'),
    path('purchase/', views.RechargeCardV.purchase, name='purchase'),
    path('payment/', views.RechargeCardV.payment, name='payment'),
    path('show/', views.RechargeCardV.show, name='show'),
    path('about/', views.RechargeCardV.about, name='about')
]

app1/models.py
from django.db import models

# Create your models here.
class RechargeCardM(models.Model):
    name=models.CharField(max_length=245,choices=((1,'MTN'),(2,'GLO'),(3,'Etisalat'),(4,'Airtel')))
    code=models.CharField(max_length=10)
    price=models.IntegerField(choices=((1,100),(2,200),(3,500),(4,1000)))

class CreditCardM(models.Model):
    cardnumber=models.CharField(verbose_name='Card Number', max_length=10)
    zipcode=models.CharField(verbose_name='Zipcode',max_length=5)
    securitycode=models.CharField(verbose_name='Security Code',max_length=3)
    nameofcardholder=models.CharField(verbose_name='Name Of Cardholder',max_length=245)
    expirydate=models.DateField(verbose_name='Expiry Date')

app1/forms.py
from django import forms
from app1.models import CreditCardM
from django.core import validators

class CreditCardF(forms.ModelForm):
    expirydate=forms.DateField(widget=forms.DateInput)
    class Meta():
        model=CreditCardM
        fields= '__all__'

app1/views.py
from django.shortcuts import render
from app1.models import RechargeCardM
from app1.forms import CreditCardF
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse

class RechargeCardV():
    code=''

    def index(request):
        return render(request,'index.html')

    def purchase(request):
         context={}
         context1={}
         nums=[1,2,3,4]
         n=0
         for num1 in nums:
            for num2 in nums:
                 context['model'+str(n)] = RechargeCardM.objects.filter(name=num1, price=num2)
                 n+=1
         try:
             if request.GET.get('0')=='100 Naira':
                 context1['sam']=context['model0'][0].code
                 RechargeCardM.code=context['model0'][0].code
                 context['model0'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('1')=='200 Naira':
                 context1['sam']=context['model1'][0].code
                 RechargeCardM.code=context['model1'][0].code
                 context['model1'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('2')=='500 Naira':
                 context1['sam']=context['model2'][0].code
                 RechargeCardM.code=context['model2'][0].code
                 context['model2'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('3')=='1000 Naira':
                 context1['sam']=context['model3'][0].code
                 RechargeCardM.code=context['model3'][0].code
                 context['model3'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('4')=='100 Naira':
                 context1['sam']=context['model4'][0].code
                 RechargeCardM.code=context['model4'][0].code
                 context['model4'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('5')=='200 Naira':
                 context1['sam']=context['model5'][0].code
                 RechargeCardM.code=context['model5'][0].code
                 context['model5'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('6')=='500 Naira':
                 context1['sam']=context['model6'][0].code
                 RechargeCardM.code=context['model6'][0].code
                 context['model6'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('7')=='1000 Naira':
                 context1['sam']=context['model7'][0].code
                 RechargeCardM.code=context['model7'][0].code
                 context['model7'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('8')=='100 Naira':
                 context1['sam']=context['model8'][0].code
                 RechargeCardM.code=context['model8'][0].code
                 context['model8'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('9')=='200 Naira':
                 context1['sam']=context['model9'][0].code
                 RechargeCardM.code=context['model9'][0].code
                 context['model9'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('10')=='500 Naira':
                 context1['sam']=context['model10'][0].code
                 RechargeCardM.code=context['model10'][0].code
                 context['model10'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('11')=='1000 Naira':
                 context1['sam']=context['model11'][0].code
                 RechargeCardM.code=context['model11'][0].code
                 context['model11'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('12')=='100 Naira':
                 context1['sam']=context['model12'][0].code
                 RechargeCardM.code=context['model12'][0].code
                 context['model12'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('13')=='200 Naira':
                 context1['sam']=context['model13'][0].code
                 RechargeCardM.code=context['model13'][0].code
                 context['model13'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('14')=='500 Naira':
                 context1['sam']=context['model14'][0].code
                 RechargeCardM.code=context['model14'][0].code
                 context['model14'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
             elif request.GET.get('15')=='1000 Naira':
                 context1['sam']=context['model15'][0].code
                 RechargeCardM.code=context['model15'][0].code
                 context['model15'][0].delete()
                 return HttpResponseRedirect(reverse("app1:payment"))
         except:
            RechargeCardM.code='Sorry there are no codes for now. You will not be charged'
            return HttpResponseRedirect(reverse("app1:payment"))

         return render(request,'purchase.html',context=context1)



    def payment(request):
         form=CreditCardF()

         if request.method=="POST":
             form=CreditCardF(request.POST)
             if form.is_valid():
                 form.save(commit=True)
                 return HttpResponseRedirect(reverse("app1:show"))
             else:
                 print('Error from invalid')
         return render(request,'payment.html',{'form':form})

    def show(request):
         dict={'code':RechargeCardM.code}
         return render(request,'about.html',context=dict)
    def about(request):
        return render(request,'about1.html')

templates/about.html
{% extends "index.html" %}
{% block bodyblock %}
<div class="jumbotron jumbotron1" >
  <h1>YOUR CODE IS: {{code}}</h1>
  <a href="{% url "app1:index" %}">Return Home</a>
</div>

{%endblock%}

templates/about1.html
{% extends "index.html" %}
{% block bodyblock %}


{%endblock%}

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>My project</title>

    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="LayoutIt!">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style1.css" %}"/>
    <link rel="shortcut icon" href="{% static "logos/logo_transparent.jpg" %}" />
  </head>
  <body>
    <div>
	<div class="row">
		<div class="col-md-12">
      <nav class='navbar navbar-default' id="two">
        <div class="container-fluid">
      <ul class="nav">
				<li class="nav-item">
          <a id='four' class="navbar-brand" href="{% url "app1:index" %}"> Home</a>
        </li>
        <li class="nav-item">
					<a id='four' class="nav-link active" href="{% url "app1:about" %}">About</a>
				</li>
				<li class="nav-item">
					<a id='four' class="nav-link active" href="{% url "app1:purchase" %}">Products</a>
				</li>
			</ul>
      </nav>
    </div>
      {% block bodyblock %}
      <div id=one>
			<div class="carousel slide" id="carousel-927306">
				<ol class="carousel-indicators">
					<li data-slide-to="0" data-target="#carousel-927306" class="active">
					</li>
					<li data-slide-to="1" data-target="#carousel-927306">
					</li>
					<li data-slide-to="2" data-target="#carousel-927306">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="carousel-item active">
						<img class="d-block w-100" alt="Carousel Bootstrap First" src="{% static "logos/bg.jpg" %}">
						<div class="carousel-caption">
							<h4 id=five>
								Samuel Is Awesome
							</h4>
							<p id=five>
                And it not one or the other, its hard truth and ridiculous grace to be known, fully known and loved by you. I'm fully known, fully known and loved by you
							</p>
              <a id=six role=button class="btn btn-success" href="{% url "app1:purchase" %}">Click to buy Credit</a>
						</div>
					</div>
					<div class="carousel-item">
						<img class="d-block w-100" alt="Carousel Bootstrap Second" src="{% static "logos/bg0.jpg" %}">
						<div class="carousel-caption">
							<h4 id=five>
								This app is gonna be so dope
							</h4>
							<p id=five>

            </p>
            <a id=six role=button class="btn btn-success" href="{% url "app1:purchase" %}">Click to buy Credit</a>
						</div>
					</div>
					<div class="carousel-item">
						<img class="d-block w-100" alt="Carousel Bootstrap Third" src="{% static "logos/bg2.jpg" %}">
						<div class="carousel-caption">
              <h4 id=five>
                I'm Hyped bro like
              </h4>
							<p id=five>
								Spirit lead me where my trust is without borders, let me walk upon the waters, wherever you may call me. Take me deeper that my feet
                would ever wander, and my faith would be made stronger in the presence of my savior.
							</p>
              <a id=six role=button class="btn btn-success" href="{% url "app1:purchase" %}">Click to buy Credit</a>
						</div>
					</div>
				</div> <a class="carousel-control-prev" href="#carousel-927306" data-slide="prev"><span class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a class="carousel-control-next" href="#carousel-927306" data-slide="next"><span class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
			</div>
    </div>
	</div>
</div>
{% endblock %}
<div class="jumbotron" id=three>
  <ul>
    <h3> <strong>Contacts</strong> </h3>
    <li>Phone:832-614-9982</li>
    <li>Linkedin:<a href="https://www.linkedin.com/in/samuel-okei-123237156/">https://www.linkedin.com/in/samuel-okei-123237156/</a></li>
    <li>Github:<a href="https://github.com/Tegasaur">https://github.com/Tegasaur</a></li>
    <li>Devpost:<a href="https://devpost.com/Tegasaur?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav">https://devpost.com/Tegasaur?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav</a></li>
    <li>Email:samuel.o.okei@ttu.edu</li>
  </ul>
</div>
</div>
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/scripts.js" %}"></script>
  </body>
</html>

templates/payment.html
{% extends "index.html" %}
{%block bodyblock%}
<div class="container">
  <div class="jumbotron" id=eight>
    <h1>Payment Information</h1>
    <form class="" action="" method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-default" name="sub" value="Submit">
    </form>
  </div>
</div>
{%endblock%}

templates/purchase.html
{% extends "index.html" %}
{%block bodyblock%}
{% load staticfiles %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6" id='ten'>
			<div class="row">


				<div class="col-md-12">
					<div class="card" id='eleven'>
						<img class="card-img-top" alt="Bootstrap Thumbnail First" src="{% static "logos/MTN-logo.jpg" %}">
						<div class="card-block">
							<h3>Prices</h3>
                <ul>
                  <form method="GET">
                  <li><input type=submit class="btn btn-default"  name="0" value="100 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default"  name="1" value="200 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default"  name="2" value="500 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default"  name="3" value="1000 Naira"></input> </li>
								</form>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
		</div>
		<div class="col-md-6" id='nine'>
			<div class="row">
				<div class="col-md-12">
					<div class="card" id='eleven'>
						<img class="card-img-top" alt="Bootstrap Thumbnail First" src="{% static "logos/glo-logo.jpg" %}">
						<div class="card-block">
							<h3>Prices</h3>
							<ul>
                  <form method="GET">
                  <li><input type=submit class="btn btn-default" name="4" value="100 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default" name="5" value="200 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default" name="6" value="500 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default" name="7" value="1000 Naira"></input> </li>
                  </form>
                </ul>
						</div>
					</div>
				</div>


			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6" id='ten'>
			<div class="row">
				<div class="col-md-12">
					<div class="card" id='eleven'>
						<img class="card-img-top" alt="Bootstrap Thumbnail First" src="{% static "logos/9Mobile-Telecom-Logo.jpg" %}">
						<div class="card-block">
							<h3>Prices</h3>
            		<ul>
                    <form method="GET">
                    <li><input type=submit class="btn btn-default" name="8" value="100 Naira"></input> </li>
                    <li><input type=submit class="btn btn-default" name="9" value="200 Naira"></input> </li>
                    <li><input type=submit class="btn btn-default" name="10" value="500 Naira"></input> </li>
                    <li><input type=submit class="btn btn-default" name="11" value="1000 Naira"></input> </li>
                    </form>
                </ul>
						</div>
					</div>
				</div>


			</div>
		</div>
		<div class="col-md-6">
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
		</div>
		<div class="col-md-6" id='nine'>
			<div class="row">
				<div class="col-md-12">
					<div class="card" id='eleven'>
						<img class="card-img-top" alt="Bootstrap Thumbnail First" src="{% static "logos/airtel-logo-red-text-horizontal.jpg" %}">
						<div class="card-block">
									<h3>Prices</h3>
									<ul>
      						<form method="GET">
                  <li><input type=submit class="btn btn-default" name="12" value="100 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default" name="13" value="200 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default" name="14" value="500 Naira"></input> </li>
                  <li><input type=submit class="btn btn-default" name="15" value="1000 Naira"></input> </li>
                  </form>
                </ul>
						</div>
					</div>
				</div>


			</div>
		</div>
	</div>
</div>
{% endblock %}